### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by LixinQian** [JerryChu/JCLeaksFinder#1]
![截屏2021-02-20 下午4 24 32](https://user-images.githubusercontent.com/14228362/108589189-3a950500-7398-11eb-9105-e18fb2b3bd2d.png)

**Comment by JerryChu** [comment]
fishhook 库的问题。
设备是 iOS14.5 beta版本吗？可以参考 https://github.com/facebook/fishhook/issues/82

**Comment by maniackk** [comment]
> fishhook 库的问题。
> 设备是 iOS14.5 beta版本吗？可以参考 [facebook/fishhook#82](https://github.com/facebook/fishhook/issues/82)

请问这是偶现crash么？

**Comment by JerryChu** [comment]
iOS14.5上目前是必现的

**Comment by maniackk** [comment]
> iOS14.5上目前是必现的

大佬有解决方案么，我测试[https://github.com/facebook/fishhook/pull/83/files](iOS14.5)这个pr，也发现了vm_protect方法似乎也有问题。我测试发现有时候vm_protect返回成功，但是事实上，相应内存并没有设置写权限成功。

**Comment by JerryChu** [comment]
> > iOS14.5上目前是必现的
> 
> 大佬有解决方案么，我测试[https://github.com/facebook/fishhook/pull/83/files](iOS14.5)这个pr，也发现了vm_protect方法似乎也有问题。我测试发现有时候vm_protect返回成功，但是事实上，相应内存并没有设置写权限成功。

目前的解决方案就是你发的这个pr，不过我还没来得及自己测试过。

**Comment by maniackk** [comment]
> > > iOS14.5上目前是必现的
> > 
> > 
> > 大佬有解决方案么，我测试[https://github.com/facebook/fishhook/pull/83/files](iOS14.5)这个pr，也发现了vm_protect方法似乎也有问题。我测试发现有时候vm_protect返回成功，但是事实上，相应内存并没有设置写权限成功。
> 
> 目前的解决方案就是你发的这个pr，不过我还没来得及自己测试过。

我这个方案已经测试了，没有问题的。iOS 14.5 具体崩溃原因可以看 https://github.com/facebook/fishhook/pull/84
