### ISSUE TITLE
输出全局对象引用链的目的是什么呢？

### ISSUE THREAD

**Issue by limaofuyuanzhang** [JerryChu/JCLeaksFinder#2]
你好，我想请问下输出全局对象引用链的目的是什么呢？是为了将MLeaksFinder错误判断的为可疑循环引用的对象剔除掉？

**Comment by JerryChu** [comment]
一句话概括：为了发生内存泄漏时，能够知道**这个对象为什么没有被释放**。

对象为什么没有被释放，有两种主要场景：
1. 泄漏对象**存在循环引用**（此时需要输出循环引用链，*FBRetainCycleDetector* 就可以做到）。
2. 泄漏对象**被全局对象引用**（此时需要输出全局对象引用链，需要使用 *JCLeaksFinder*）。
